### ISSUE TITLE
Possibility to train RNNs with sequence of length 1

### ISSUE THREAD

**Issue by JankowskiDaniel** [JankowskiDaniel/Neural-Deep-Retina#51]
To train RNNs with a sequence of length 1 we have to modify the logic in encoders:

The current implementation:
```python
def forward(self, x):
        if self.seq_len > 1:
            latent_seq = []
            # batch
            for t in range(self.seq_len):
                x_t = self.features(x[:, t])
                x_t = x_t.view(x_t.size(0), -1)  # (batch_size, 512)
                latent_seq.append(x_t)

            x = torch.stack(latent_seq, dim=1)  # (batch_size, seq_len, 512)

        else:  # single image, not processed as a sequence
            x = self.features(x)
            x = x.view(x.size(0), -1)  # Flatten the tensor

        return x
```
A new implementation:
```python
def forward(self, x):
        if self.seq_len >= 1:
            latent_seq = []
            # batch
            for t in range(self.seq_len):
                x_t = self.features(x[:, t])
                x_t = x_t.view(x_t.size(0), -1)  # (batch_size, 512)
                latent_seq.append(x_t)

            x = torch.stack(latent_seq, dim=1)  # (batch_size, seq_len, 512)

        else:  # single image, not processed as a sequence
            x = self.features(x)
            x = x.view(x.size(0), -1)  # Flatten the tensor

        return x
```

It would require logic changes in the config:
```yaml
DATA:
  data_handler: BaselineSeqRGBDataset # "H5Dataset", "H5SeqDataset", "BaselineRGBDataset", "BaselineSeqRGBDataset"
  img_shape: [40, 50, 50]
  path: data/neural_code_data/ganglion_cell_data/15-10-07/naturalscene.h5
  response_type: firing_rate_10ms
  is_rgb: False
  seq_len: 1
  prediction_step: 0
  subset_size: 2000
```
From now, `seq_len: 1` would mean that we are operating on a sequence of length 1, and the predictor should take sequential input.
Therefore, if we want to operate on a single images, not sequences, the `seq_len: 0` parameter should be used.
